export const mockUser = {
  login: 'sandeep-garg',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/37319124?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/sandeep8080',
  html_url: 'https://github.com/sandeep8080',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'Sandeep Garg',
  company: 'TCS',
  blog: 'www.sandeepgarg.com',
  location: 'Delhi, India',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'sandeep991',
  public_repos: 152,
  public_gists: 5,
  followers: 1495,
  following: 10,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
